include ../../build/modules.mk

MODULE = globalModule
FILENAME = ${MODULE}.js
SOURCE = ${SOURCE_DIR}/${MODULE}.js
PRODUCTION = ${PRODUCTION_DIR}/${FILENAME}
DEVELOPMENT = ${DEVELOPMENT_DIR}/${FILENAME}

all:
	cp ${SOURCE} ${DEVELOPMENT}
	${UGLIFYJS} ${SOURCE} > ${PRODUCTION}
